#!/usr/bin/env python3
"""
strip_java_for_ai.py — 生成 COMSOL .java 的 AI 阅读专用版

剥离 Solver Configurations、Probes/Cut*、超长 setIndex 等对 AI 建模不必要的
section,大幅压缩文件体积,便于在 Copilot Chat / Claude 等工具中作为上下文使用。

⚠️ 重要: 输出的文件**不能直接编译**,仅用于 AI 阅读理解。要回写 COMSOL 必须用原始
   .java 或 _full 版本。

用法:
    python strip_java_for_ai.py <input.java> <output.java> [选项]

例:
    python strip_java_for_ai.py cell_v3.java cell_v3_for_ai.java
    python strip_java_for_ai.py cell_v3.java cell_v3_for_ai.java --keep-probes
    python strip_java_for_ai.py cell_v3.java cell_v3_for_ai.java --aggressive

剥离规则 (按强度递增):
    默认:      剥离 model.sol(...) 求解器配置块
    --keep-probes: 不剥离 Probes/Cut* 节点 (默认会剥离调试节点)
    --aggressive:  额外剥离超长 setIndex 数据块 (>500 字符的行)

依赖: 仅 Python 标准库
兼容: Python 3.7+
"""

import argparse
import os
import re
import sys


# 求解器section识别
SOL_LINE = re.compile(r'^\s*model\.sol\(')

# Result下的调试节点 (Probes/Cut Lines/Planes/Points)
DEBUG_NODE_PATTERNS = [
    re.compile(r'model\.result\(\)\.numerical\(\)\.create\("[^"]+",\s*"Probe'),
    re.compile(r'model\.result\(\)\.dataset\(\)\.create\("[^"]+",\s*"CutLine'),
    re.compile(r'model\.result\(\)\.dataset\(\)\.create\("[^"]+",\s*"CutPlane'),
    re.compile(r'model\.result\(\)\.dataset\(\)\.create\("[^"]+",\s*"CutPoint'),
]


def strip_solver_blocks(lines):
    """
    剥离连续的 model.sol(...) 行块。

    策略: 扫描时,遇到 model.sol 行就找该block的结束位置
    (last consecutive sol line, 允许中间有空行)。如果block > 阈值,替换为占位注释。
    """
    output = []
    i = 0
    n = len(lines)
    n_blocks = 0
    n_stripped_lines = 0
    n_stripped_chars = 0

    BLOCK_THRESHOLD = 20  # 小于此行数的不剥离 (避免误伤简短的sol配置)

    while i < n:
        line = lines[i]
        if SOL_LINE.match(line):
            # 找block结束
            block_start = i
            j = i
            last_sol = i
            while j < n:
                if SOL_LINE.match(lines[j]):
                    last_sol = j
                    j += 1
                elif lines[j].strip() == '':
                    j += 1  # 跳过block内的空行
                else:
                    break
            block_end = last_sol + 1
            block_lines = block_end - block_start

            if block_lines >= BLOCK_THRESHOLD:
                # 计算剥离的字符数
                block_chars = sum(len(lines[k]) for k in range(block_start, block_end))
                n_stripped_chars += block_chars
                n_stripped_lines += block_lines
                n_blocks += 1
                # 占位注释
                output.append(
                    f"    // ====================================================================\n"
                    f"    // Solver Configuration Block #{n_blocks}: {block_lines} lines stripped for AI reading.\n"
                    f"    // Original size: {block_chars/1024:.1f} KB. Regenerated by COMSOL on recompile.\n"
                    f"    // (此求解器配置块已剥离,COMSOL 重新编译时会自动生成 sol 节点)\n"
                    f"    // ====================================================================\n"
                )
                i = block_end
            else:
                # block太短,不剥离
                output.append(line)
                i += 1
        else:
            output.append(line)
            i += 1

    return output, n_blocks, n_stripped_lines, n_stripped_chars


def strip_debug_nodes(lines):
    """
    剥离 Probes、Cut Lines/Planes/Points 等调试节点。

    策略: 找到 Probe/Cut* 的 create 行,然后从该行开始直到下一个 result/numerical/dataset
    create (或文件末尾) 之间的所有内容都剥离。
    """
    output = []
    i = 0
    n = len(lines)
    n_nodes_stripped = 0
    n_lines_stripped = 0

    # 任意新 create 调用,表示当前节点配置结束
    NEXT_CREATE = re.compile(r'\.create\("[^"]+",')

    while i < n:
        line = lines[i]
        is_debug = any(p.search(line) for p in DEBUG_NODE_PATTERNS)

        if is_debug:
            # 找此调试节点的所有配置行 (直到下一个create或section换)
            block_start = i
            j = i + 1
            while j < n:
                # 下一个不同对象的create → 当前debug节点结束
                # 或者出现明显的section换 (model.study 之类)
                if NEXT_CREATE.search(lines[j]):
                    break
                # 简单启发: 空行后跟新的 result/study 调用
                if lines[j].strip() == '' and j+1 < n:
                    if 'model.' in lines[j+1] and 'numerical' not in lines[j+1]:
                        break
                j += 1

            n_lines_stripped += (j - block_start)
            n_nodes_stripped += 1
            output.append(
                f"    // [Debug node stripped: {(j-block_start)} lines, "
                f"原始行: {block_start+1}]\n"
            )
            i = j
        else:
            output.append(line)
            i += 1

    return output, n_nodes_stripped, n_lines_stripped


def strip_long_setindex(lines, threshold=500):
    """
    剥离超长的 setIndex 行 (通常是嵌入的插值表数据)。

    threshold: 行长度阈值 (字符数),超过此长度且包含 setIndex 的行会被替换。
    """
    output = []
    n_stripped = 0
    n_chars_stripped = 0

    for line in lines:
        if len(line) > threshold and 'setIndex' in line:
            n_stripped += 1
            n_chars_stripped += len(line)
            output.append(
                f"    // [Long setIndex stripped: {len(line)} chars, likely embedded interpolation data]\n"
            )
        else:
            output.append(line)

    return output, n_stripped, n_chars_stripped


def add_ai_header(lines, input_path, stats):
    """在文件顶部加 AI-only 警告 header"""
    header = [
        "/*\n",
        " * ====================================================================\n",
        " * AI-READING-ONLY VERSION — NOT COMPILABLE\n",
        " * ====================================================================\n",
        " * \n",
        f" * Generated from: {os.path.basename(input_path)}\n",
        " * Tool: strip_java_for_ai.py (comsol-battery-model-automation skill)\n",
        " * \n",
        " * 本文件是为 AI Agent (Claude/Copilot/etc.) 阅读优化的精简版本。\n",
        " * 已剥离:\n",
        f" *   - 求解器配置 (Solver Configurations): {stats.get('sol_blocks',0)} 块, {stats.get('sol_lines',0)} 行\n",
        f" *   - 调试节点 (Probes/Cut Lines/Planes): {stats.get('debug_nodes',0)} 个\n",
        f" *   - 超长 setIndex 行: {stats.get('setindex_count',0)} 行\n",
        " * \n",
        " * ⚠️ 此文件不能用 comsolcompile 直接编译。要回写 COMSOL 必须用原始 .java。\n",
        " * \n",
        " * 详见 references/java_export_slimming.md\n",
        " * ====================================================================\n",
        " */\n",
        "\n",
    ]
    return header + lines


def main():
    parser = argparse.ArgumentParser(
        description="生成 COMSOL .java 的 AI 阅读专用版 (剥离 Solver/Probes/嵌入数据)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="详见 references/java_export_slimming.md"
    )
    parser.add_argument('input', help='输入 .java 文件')
    parser.add_argument('output', help='输出 .java 文件 (AI专用版)')
    parser.add_argument('--keep-probes', action='store_true',
                        help='保留 Probes/Cut* 节点 (默认剥离)')
    parser.add_argument('--aggressive', action='store_true',
                        help='额外剥离超长 setIndex 行 (>500字符)')
    parser.add_argument('--threshold', type=int, default=500,
                        help='--aggressive 模式下的字符长度阈值 (默认500)')

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"ERROR: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    orig_size = os.path.getsize(args.input)

    with open(args.input, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    n_orig_lines = len(lines)

    stats = {}

    # 1. 剥离 Solver Configurations
    print("剥离 Solver Configurations ...")
    lines, n_blocks, n_sol_lines, n_sol_chars = strip_solver_blocks(lines)
    stats['sol_blocks'] = n_blocks
    stats['sol_lines'] = n_sol_lines
    print(f"  → {n_blocks} 块, {n_sol_lines} 行, {n_sol_chars/1024:.1f} KB")

    # 2. 剥离调试节点
    if not args.keep_probes:
        print("剥离 Probes/Cut Lines/Planes/Points ...")
        lines, n_debug, n_debug_lines = strip_debug_nodes(lines)
        stats['debug_nodes'] = n_debug
        print(f"  → {n_debug} 个节点, {n_debug_lines} 行")

    # 3. 剥离超长 setIndex (--aggressive)
    if args.aggressive:
        print(f"剥离超长 setIndex (>{args.threshold} 字符) ...")
        lines, n_si, n_si_chars = strip_long_setindex(lines, args.threshold)
        stats['setindex_count'] = n_si
        print(f"  → {n_si} 行, {n_si_chars/1024:.1f} KB")

    # 4. 加 AI-only header
    lines = add_ai_header(lines, args.input, stats)

    # 5. 写出
    with open(args.output, 'w', encoding='utf-8') as f:
        f.writelines(lines)

    new_size = os.path.getsize(args.output)

    print()
    print("=" * 60)
    print(f" 完成: {args.input} → {args.output}")
    print("=" * 60)
    print(f"原始: {orig_size/1024:>10.1f} KB  ({n_orig_lines:,} 行)")
    print(f"输出: {new_size/1024:>10.1f} KB  ({len(lines):,} 行)")
    reduction = 100 * (orig_size - new_size) / orig_size if orig_size > 0 else 0
    print(f"减少: {(orig_size-new_size)/1024:>10.1f} KB  ({reduction:.1f}%)")
    print()
    print(f"⚠️  {args.output} 仅用于 AI 阅读,不能直接编译。")
    print(f"   回写 COMSOL 时使用原始的 {args.input}。")
    print()


if __name__ == '__main__':
    main()
